// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Como Next: primero .env.development.local (lo escribe `vercel env pull`),
// luego .env. dotenv no pisa variables ya definidas, así que gana el primero.
loadEnv({ path: [".env.development.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Solo la usa el CLI (migrate/seed/studio): conexión directa a Neon, sin
    // pgbouncer. El runtime usa el adapter pg con DATABASE_URL (pooled).
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
